parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
  ecmaVersion: 2019
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
plugins:
  - "@typescript-eslint"
  - prettier
extends:
  # https://github.com/eslint/eslint/blob/master/conf/eslint-recommended.js
  - eslint:recommended
  # https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin
  - plugin:@typescript-eslint/recommended
  # prettier ueberschreibt vorherige Konfigurationseinstellungen
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
env:
  node: true
  es6: true
rules:
  # https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#supported-rules
  # https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin/docs/rules
  "@typescript-eslint/array-type":
    - error
    - default: generic
  "@typescript-eslint/await-thenable": error
  "@typescript-eslint/brace-style": error
  "@typescript-eslint/consistent-type-definitions":
    - error
    - interface
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/explicit-member-accessibility": off
  "@typescript-eslint/func-call-spacing": error
  "@typescript-eslint/interface-name-prefix": off
  "@typescript-eslint/member-naming": error
  "@typescript-eslint/member-ordering": error
  "@typescript-eslint/no-empty-function": error
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-extra-parens": error
  "@typescript-eslint/no-extraneous-class": error
  "@typescript-eslint/no-floating-promises": error
  "@typescript-eslint/no-for-in-array": error
  "@typescript-eslint/no-magic-numbers":
    - error
    - ignoreReadonlyClassProperties: true
      ignoreArrayIndexes: true
      enforceConst: true
      ignore:
        - 0
        - 1
        - -1
  "@typescript-eslint/no-misused-promises": error
  "@typescript-eslint/no-parameter-properties": off
  "@typescript-eslint/no-require-imports": error
  "@typescript-eslint/no-this-alias": error
  "@typescript-eslint/no-type-alias": error
  "@typescript-eslint/no-unnecessary-condition": error
  "@typescript-eslint/no-unnecessary-qualifier": error
  "@typescript-eslint/no-unnecessary-type-arguments": error
  "@typescript-eslint/no-unnecessary-type-assertion": error
  "@typescript-eslint/no-useless-constructor": error
  "@typescript-eslint/prefer-for-of": error
  "@typescript-eslint/prefer-includes": error
  "@typescript-eslint/prefer-readonly": error
  "@typescript-eslint/prefer-regexp-exec": error
  "@typescript-eslint/prefer-string-starts-ends-with": error
  "@typescript-eslint/require-array-sort-compare": error
  "@typescript-eslint/require-await": error
  "@typescript-eslint/restrict-plus-operands": error
  "@typescript-eslint/semi": error
  "@typescript-eslint/strict-boolean-expressions": error
  "@typescript-eslint/triple-slash-reference": error
  "@typescript-eslint/type-annotation-spacing": error
  "@typescript-eslint/unbound-method":
    - error
    - ignoreStatic: true
  "@typescript-eslint/unified-signatures": error
  array-bracket-newline:
    - error
    - multiline: true
  array-bracket-spacing: error
  arrow-body-style:
    - error
    - as-needed
  arrow-parens:
    - error
    - as-needed
  arrow-spacing: error
  block-scoped-var: error
  block-spacing: error
  # siehe @typescript-eslint/brace-style
  brace-style: 0
  callback-return: error
  camelcase: error
  comma-dangle:
    - error
    - always-multiline
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  consistent-this: error
  curly: error
  default-case: error
  default-param-last: error
  dot-notation: error
  eqeqeq: error
  eol-last: error
  for-direction: error
  # siehe @typescript-eslint/func-call-spacing
  func-call-spacing: 0
  func-name-matching: error
  func-names:
    - error
    - never
  func-style: error
  getter-return: error
  global-require: error
  handle-callback-err: error
  key-spacing: error
  keyword-spacing: error
  line-comment-position: error
  linebreak-style:
    - error
    - windows
  max-classes-per-file: error
  max-depth: error
  max-len:
    - error
    - ignoreComments: true
      ignoreTrailingComments: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
  max-lines: error
  max-lines-per-function:
    - error
    - max: 60
  max-nested-callbacks:
    - error
    - max: 4
  max-params: error
  max-statements:
    - error
    - max: 25
  max-statements-per-line: error
  new-cap: error
  new-parens: error
  no-alert: error
  no-array-constructor: error
  no-bitwise: error
  no-buffer-constructor: error
  no-caller: error
  no-confusing-arrow: error
  no-console: 0
  no-continue: error
  no-duplicate-imports: error
  no-else-return: error
  no-empty-function: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-import-assign: error
  no-invalid-this: error
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  # siehe "@typescript-eslint/no-magic-numbers
  # no-magic-numbers: ...
  no-mixed-requires: error
  no-multi-assign: error
  no-multi-spaces: error
  no-multiple-empty-lines: error
  no-negated-condition: error
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-wrappers: error
  no-param-reassign: error
  no-path-concat: error
  no-process-env: error
  no-process-exit: error
  no-proto: error
  no-restricted-properties: error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow: error
  no-shadow-restricted-names: error
  no-sync: error
  no-tabs: error
  no-template-curly-in-string: error
  no-throw-literal: error
  no-trailing-spaces: error
  no-undef-init: error
  no-underscore-dangle:
    - error
    - allow:
        - _id
        - __v
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unused-expressions: error
  no-use-before-define:
    - error
    - functions: false
      classes: false
  no-useless-call: error
  no-useless-catch: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-rename: error
  no-useless-return: error
  no-void: error
  no-whitespace-before-property: error
  no-with: error
  nonblock-statement-body-position: error
  object-curly-newline:
    - error
    - multiline: true
  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: true
  object-shorthand: error
  one-var:
    - error
    - never
  one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak: error
  padded-blocks:
    - error
    - never
  prefer-arrow-callback: error
  prefer-destructuring: error
  prefer-numeric-literals: error
  prefer-object-spread: error
  prefer-promise-reject-errors: error
  prefer-regex-literals: error
  prefer-rest-params: error
  prefer-template: error
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
  radix: error
  require-atomic-updates: error
  require-await: error
  require-unicode-regexp: error
  rest-spread-spacing: error
  semi-spacing: error
  sort-imports: error
  space-before-blocks: error
  space-before-function-paren:
    - error
    - anonymous: never
      asyncArrow: always
      named: never
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  strict: error
  switch-colon-spacing: error
  symbol-description: error
  template-curly-spacing: error
  wrap-iife: error
  yield-star-spacing: error
  yoda:
    - error
    - never
